version: "3.8"

services:
        nginx_load_balancer:
                image: nginx:latest
                ports:
                        - "80:80"
                volumes:
                        - "./nginx/default.conf:/etc/nginx/nginx.conf"
                depends_on:
                        - web1
                        - web2
                        - web3
        web1:
                image: chatapp
                restart: always
                container_name: docker_chat_app_1
                environment:
                        - MONGO_URI=${MONGO_URI}
                ports:
                        - "5001:5000"
                depends_on:
                        - db
        web2:
                image: chatapp
                restart: always
                container_name: docker_chat_app_2
                environment:
                        - MONGO_URI=${MONGO_URI}
                ports:
                        - "5002:5000"
                depends_on:
                        - db
        web3:
                image: chatapp
                restart: always
                container_name: docker_chat_app_3
                environment:
                        - MONGO_URI=${MONGO_URI}
                ports:
                        - "5003:5000"
                depends_on:
                        - db
        db:
                container_name: docker_chat_app_db
                image: mongo:5.0.3
                ports:
                        - "27017:27017"
