version: "3.8"

services:
        chat-app:
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                container_name: docker_chat_app
                environment:
                        - MONGO_URI=mongodb+srv://leksyking:leksyking7@cluster1.hrb9b.mongodb.net/chatman
                ports:
                        - "5000:5000"
                depends_on:
                        - db
        db:
                image: mongo:5.0.3
                ports:
                        - "27017:27017"
