name: 🚀 Test and Deploy Week7's app on push

on:
        push:
                branches:
                        - main

jobs:
        build:
                name: Deploy app
                runs-on: ubuntu-latest
                steps:
                        - name: 🚚 Get latest code
                          uses: actions/checkout@v3

                        - name: Use Node.js 16
                          uses: actions/setup-node@v3
                          with:
                                  node-version: "16"

                        - name: Cache npm dependencies
                          uses: actions/cache@v3
                          id: cache-node-modules
                          with:
                                  path: "**/node_modules"
                                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

                        - name: 🔨 Install Dependencies
                          if: steps.npm-cache.outputs.cache-hit != 'true'
                          run: |
                                  cd uptick-talent-fellowship-week7 && npm install
                                  git reset --hard

                        - name: Run tests
                          run: |
                                  cd uptick-talent-fellowship-week7 && npm run test

                        - uses: actions/checkout@v2
                        - uses: superfly/flyctl-actions/setup-flyctl@master
                        - run: flyctl deploy --remote-only
                          env:
                                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
